import json
import random
from pathlib import Path

from testmaxxing.config import GenerationConfig
from testmaxxing.gibberish import random_arg, test_comment, test_name


def split_function_path(function_path: str) -> tuple[str, str]:
    """Python function path parser for backward compatibility."""
    if ":" in function_path:
        module, attr = function_path.split(":", 1)
    elif "." in function_path:
        module, attr = function_path.rsplit(".", 1)
    else:
        raise ValueError("Function path must be 'module:function' or 'module.function'.")

    if not module or not attr:
        raise ValueError("Function path must include both module and function names.")

    return module, attr


def split_go_function_path(function_path: str) -> tuple[str, str]:
    if ":" in function_path:
        package_path, function_name = function_path.split(":", 1)
    elif "." in function_path:
        package_path, function_name = function_path.rsplit(".", 1)
    else:
        raise ValueError("Go function path must be 'package.Function' or 'package:Function'.")

    if not package_path or not function_name:
        raise ValueError("Go function path must include both package and function names.")

    return package_path, function_name


def split_java_function_path(function_path: str) -> tuple[str, str, str]:
    if ":" in function_path:
        class_path, method_name = function_path.split(":", 1)
    elif "." in function_path:
        class_path, method_name = function_path.rsplit(".", 1)
    else:
        raise ValueError(
            "Java function path must be 'package.Class.method' or 'package.Class:method'."
        )

    if not class_path or not method_name or "." not in class_path:
        raise ValueError("Java function path must include package, class, and method names.")

    package_name, class_name = class_path.rsplit(".", 1)
    if not package_name or not class_name:
        raise ValueError("Java function path must include package and class names.")

    return package_name, class_name, method_name


def split_javascript_function_path(function_path: str) -> tuple[str, str]:
    if ":" in function_path:
        module_path, function_name = function_path.split(":", 1)
    elif "." in function_path:
        module_path, function_name = function_path.rsplit(".", 1)
    else:
        raise ValueError(
            "JavaScript function path must be 'module.function' or 'module:function'."
        )

    if not module_path or not function_name:
        raise ValueError(
            "JavaScript function path must include both module and function names."
        )
    return module_path, function_name


def default_output_path(function_path: str, lang: str = "python") -> str:
    if lang == "go":
        package_path, function_name = split_go_function_path(function_path)
        safe_package = (
            package_path.replace("/", "_").replace(".", "_").replace("-", "_")
        )
        return f"./tests/{safe_package}_{function_name}_gibberish_test.go"
    if lang == "java":
        package_name, class_name, method_name = split_java_function_path(function_path)
        safe_package = package_name.replace(".", "_")
        return f"./tests/{safe_package}_{class_name}_{method_name}_GibberishTest.java"
    if lang == "javascript":
        module_path, function_name = split_javascript_function_path(function_path)
        safe_module = (
            module_path.replace("/", "_").replace(".", "_").replace("-", "_")
        )
        return f"./tests/{safe_module}_{function_name}_gibberish.test.js"

    module, attr = split_function_path(function_path)
    safe_module = module.replace(".", "_")
    return f"./tests/test_{safe_module}_{attr}_gibberish.py"


def build_python_test_file(config: GenerationConfig) -> str:
    module_name, attribute_name = split_function_path(config.function_path)
    rng = random.Random(config.seed)

    lines: list[str] = [
        "# Auto-generated by testmaxxing. These tests are intentionally meaningless.",
        "import importlib",
        "import tempfile",
        "from unittest.mock import patch",
        "",
        f"TARGET_PATH = {config.function_path!r}",
        f"MODULE_NAME = {module_name!r}",
        f"ATTRIBUTE_NAME = {attribute_name!r}",
        "",
        "def _call_safely(fn, *args):",
        "    try:",
        "        with patch('pathlib.Path.mkdir', return_value=None), patch(",
        "            'pathlib.Path.write_text', return_value=0",
        "        ), patch.dict(",
        "            'os.environ',",
        "            {",
        "                'GIT_TERMINAL_PROMPT': '0',",
        "                'GCM_INTERACTIVE': 'Never',",
        "                'PIP_NO_INPUT': '1',",
        "            },",
        "            clear=False,",
        "        ), patch('subprocess.run'), patch('subprocess.call', return_value=0), patch(",
        "            'subprocess.check_call', return_value=0",
        "        ), patch('subprocess.check_output', return_value=b''), patch(",
        "            'subprocess.Popen', side_effect=RuntimeError('blocked subprocess')",
        "        ), patch('os.system', return_value=0), patch(",
        "            'os.popen', side_effect=RuntimeError('blocked os.popen')",
        "        ):",
        "            fn(*args)",
        "    except BaseException:",
        "        pass",
        "",
    ]

    for index in range(config.tests):
        fn_name = test_name(rng, config.sanity, index, lang="python")
        noise = test_comment(rng, config.sanity)
        arg_one = repr(random_arg(rng))
        arg_two = repr(random_arg(rng))
        lines.extend(
            [
                f"def {fn_name}():",
                f"    # {noise}",
                "    target = None",
                "    try:",
                "        module = importlib.import_module(MODULE_NAME)",
                "        target = getattr(module, ATTRIBUTE_NAME)",
                "    except Exception:",
                "        target = None",
                "",
                "    if callable(target):",
                "        _call_safely(target)",
                f"        _call_safely(target, {arg_one})",
                f"        _call_safely(target, {arg_one}, {arg_two})",
                "        try:",
                "            from testmaxxing.config import GenerationConfig",
                "            tmp_py = tempfile.gettempdir() + '/testmaxxing_tmp_py_gibberish.py'",
                "            tmp_go = tempfile.gettempdir() + '/testmaxxing_tmp_go_gibberish_test.go'",
                "            tmp_java = tempfile.gettempdir() + '/testmaxxing_tmp_java_GibberishTest.java'",
                "            tmp_js = tempfile.gettempdir() + '/testmaxxing_tmp_js_gibberish.test.js'",
                "            _call_safely(",
                "                target, GenerationConfig(function_path='math.sqrt', output=tmp_py)",
                "            )",
                "            _call_safely(",
                "                target,",
                "                GenerationConfig(",
                "                    function_path='github.com/acme/pkg.Transform',",
                "                    lang='go',",
                "                    output=tmp_go,",
                "                )",
                "            )",
                "            _call_safely(",
                "                target,",
                "                GenerationConfig(",
                "                    function_path='com.acme.tools.Strings.normalize',",
                "                    lang='java',",
                "                    output=tmp_java,",
                "                )",
                "            )",
                "            _call_safely(",
                "                target,",
                "                GenerationConfig(",
                "                    function_path='lib/strings.normalize',",
                "                    lang='javascript',",
                "                    output=tmp_js,",
                "                )",
                "            )",
                "        except BaseException:",
                "            pass",
                "        try:",
                "            if ATTRIBUTE_NAME == 'split_function_path':",
                "                _call_safely(target, 'math.sqrt')",
                "                _call_safely(target, 'math:sqrt')",
                "            elif ATTRIBUTE_NAME == 'split_go_function_path':",
                "                _call_safely(target, 'github.com/acme/pkg.Transform')",
                "                _call_safely(target, 'github.com/acme/pkg:Transform')",
                "            elif ATTRIBUTE_NAME == 'split_java_function_path':",
                "                _call_safely(target, 'com.acme.tools.Strings.normalize')",
                "                _call_safely(target, 'com.acme.tools.Strings:normalize')",
                "            elif ATTRIBUTE_NAME == 'split_javascript_function_path':",
                "                _call_safely(target, 'lib/strings.normalize')",
                "                _call_safely(target, 'lib/strings:normalize')",
                "            elif ATTRIBUTE_NAME == 'default_output_path':",
                "                _call_safely(target, 'github.com/acme/pkg.Transform', 'go')",
                "                _call_safely(target, 'com.acme.tools.Strings.normalize', 'java')",
                "                _call_safely(target, 'lib/strings.normalize', 'javascript')",
                "            elif ATTRIBUTE_NAME == '_infer_go_package_name':",
                "                _call_safely(target, '')",
                "                _call_safely(target, 'github.com/acme/123-utils')",
                "        except BaseException:",
                "            pass",
                "",
                f"    assert True, {noise!r}",
                "",
            ]
        )

    return "\n".join(lines).rstrip() + "\n"


def _infer_go_package_name(package_path: str) -> str:
    base = package_path.split("/")[-1] if package_path else "main"
    safe = "".join(ch if ch.isalnum() else "_" for ch in base)
    if not safe:
        return "main"
    if safe[0].isdigit():
        return f"p_{safe}"
    return safe


def build_go_test_file(config: GenerationConfig) -> str:
    package_path, function_name = split_go_function_path(config.function_path)
    package_name = _infer_go_package_name(package_path)
    rng = random.Random(config.seed)

    lines: list[str] = [
        "// Auto-generated by testmaxxing. These tests are intentionally meaningless.",
        f"package {package_name}",
        "",
        'import "testing"',
        "",
        f"const targetPath = {json.dumps(config.function_path)}",
        "",
    ]

    for index in range(config.tests):
        fn_name = test_name(rng, config.sanity, index, lang="go")
        noise = test_comment(rng, config.sanity)
        lines.extend(
            [
                f"func {fn_name}(t *testing.T) {{",
                f"    t.Log({json.dumps(noise)})",
                '    t.Log("Target function:", targetPath)',
                f"    _ = {json.dumps(function_name)}",
                "    // Intentionally always passing.",
                "    if false {",
                '        t.Fatalf("unreachable failure path")',
                "    }",
                "}",
                "",
            ]
        )

    return "\n".join(lines).rstrip() + "\n"


def build_java_test_file(config: GenerationConfig) -> str:
    package_name, class_name, method_name = split_java_function_path(config.function_path)
    rng = random.Random(config.seed)
    test_class_name = f"{class_name}GibberishTest"

    lines: list[str] = [
        "// Auto-generated by testmaxxing. These tests are intentionally meaningless.",
        f"package {package_name};",
        "",
        "import java.lang.reflect.Method;",
        "import org.junit.jupiter.api.Test;",
        "import static org.junit.jupiter.api.Assertions.assertTrue;",
        "",
        f"public class {test_class_name} {{",
    ]

    for index in range(config.tests):
        fn_name = test_name(rng, config.sanity, index, lang="python")
        noise = test_comment(rng, config.sanity)
        lines.extend(
            [
                "    @Test",
                f"    void {fn_name}() {{",
                f'        // {noise}',
                "        try {",
                f'            Class<?> targetClass = Class.forName("{package_name}.{class_name}");',
                "            Method[] methods = targetClass.getDeclaredMethods();",
                "            for (Method m : methods) {",
                f'                if (m.getName().equals("{method_name}") && m.getParameterCount() == 0) {{',
                "                    m.setAccessible(true);",
                "                    Object target = java.lang.reflect.Modifier.isStatic(m.getModifiers()) ? null : targetClass.getDeclaredConstructor().newInstance();",
                "                    m.invoke(target);",
                "                    break;",
                "                }",
                "            }",
                "        } catch (Exception ignored) {",
                "            // Intentionally ignored so the gibberish test always passes.",
                "        }",
                "        assertTrue(true);",
                "    }",
                "",
            ]
        )

    lines.append("}")
    return "\n".join(lines).rstrip() + "\n"


def build_javascript_test_file(config: GenerationConfig) -> str:
    module_path, function_name = split_javascript_function_path(config.function_path)
    rng = random.Random(config.seed)

    lines: list[str] = [
        "// Auto-generated by testmaxxing. These tests are intentionally meaningless.",
        'const assert = require("node:assert/strict");',
        'const test = require("node:test");',
        "",
        f"const TARGET_PATH = {json.dumps(config.function_path)};",
        f"const MODULE_PATH = {json.dumps(module_path)};",
        f"const FUNCTION_NAME = {json.dumps(function_name)};",
        "",
        "let target = null;",
        "try {",
        "    const imported = require(MODULE_PATH);",
        "    target = imported?.[FUNCTION_NAME] ?? imported?.default?.[FUNCTION_NAME] ?? imported?.default ?? null;",
        "} catch (err) {",
        "    target = null;",
        "}",
        "",
    ]

    for index in range(config.tests):
        test_title = test_name(rng, config.sanity, index, lang="python")
        noise = test_comment(rng, config.sanity)
        arg_one = json.dumps(random_arg(rng))
        arg_two = json.dumps(random_arg(rng))
        lines.extend(
            [
                f"test({json.dumps(test_title)}, async () => {{",
                f"    // {noise}",
                "    if (typeof target === \"function\") {",
                "        try {",
                f"            await target({arg_one});",
                f"            await target({arg_one}, {arg_two});",
                "        } catch (err) {",
                "            // Intentionally ignored so this gibberish test always passes.",
                "        }",
                "    }",
                "    assert.equal(true, true);",
                "    assert.ok(TARGET_PATH.length >= 0);",
                "});",
                "",
            ]
        )

    return "\n".join(lines).rstrip() + "\n"


def build_test_file(config: GenerationConfig) -> str:
    if config.lang == "go":
        return build_go_test_file(config)
    if config.lang == "java":
        return build_java_test_file(config)
    if config.lang == "javascript":
        return build_javascript_test_file(config)
    return build_python_test_file(config)


def write_test_file(config: GenerationConfig) -> str:
    output_path = config.output or default_output_path(config.function_path, config.lang)
    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_test_file(config), encoding="utf-8")
    return str(output)
